import "styled/index.scss";

import React from "react";
import Head from "next/head";
import { useServerInsertedHTML } from "next/navigation";
import StyledSheet from "./stylesheets";

import Header from "components/header";
import Sidebar from "components/sidebar";
import Footer from "components/footer";

import { getCssText } from "configs/stitches.config";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <StyledSheet />
      </head>
      <body>
        <Header />
        <div className="container">
          <div className="d-flex justify-content-between page-content">
            <Sidebar />
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
